apiVersion: v1
kind: Service
metadata:
  name: {{ template "etcd.fullname" . }}
  labels:
    {{- include "etcd.labels" . | nindent 4 }}
spec:
  publishNotReadyAddresses: true
  clusterIP: None
  ports:
  - port: {{ .Values.peerPort }}
    name: etcd-server
  - port: {{ .Values.clientPort }}
    name: etcd-client
  selector:
    {{- include "etcd.server.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-client" (include "etcd.fullname" .) }}
  labels:
    {{- include "etcd.labels" . | nindent 4 }}
spec:
  ports:
  - port: {{ .Values.clientPort }}
    name: etcd-client
  selector:
    {{- include "etcd.server.selectorLabels" . | nindent 4 }}
